import type { Metadata } from "next";
import { Syne, DM_Sans, Sora, Geist } from 'next/font/google'
import "./globals.css";
import { Toaster } from 'sonner'
import { cn } from "@/lib/utils";
import { ProfileProvider } from '@/context/ProfileContext'
import { ScrollToTopButton } from '@/components/shared/ScrollToTopButton'

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const syne = Syne({
  subsets: ['latin'],
  weight: ['500', '700', '800'],
  variable: '--font-syne',
  display: 'swap',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-dm-sans',
  display: 'swap',
})

const sora = Sora({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-sora',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProfileProvider>
      <html
        lang="en"
        className={cn(syne.variable, dmSans.variable, sora.variable, "font-sans", geist.variable)}
      >
        <body className="min-h-full flex flex-col">
          {children}
          <ScrollToTopButton />
          <Toaster richColors position="top-right" />
        </body>
      </html>
    </ProfileProvider>
  );
}
